/// Flutter icons MyFlutterApp
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';
  static const String? _kFontPkg = null;

  static const IconData tap_ate3018t6hns = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData painter_h5t7do9mj0zg = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData electrician_u1nm1im4g99j = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings_p9d66eozgb85 = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData online_services_jeexdh41a2r4 = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData carpenter_ial5q6o1hk6m = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
